name: "Typst Compiler"
description: "A GitHub Action for compiling Typst files to PDF's using the latest Typst release."
icon: 'file-plus'
color: 'purple'
inputs:
  source_paths:
    description: "Space separated list of paths to the .typ files"
    required: true
  output_paths:
    description: "Space separated list of output paths (must be .pdf) (defaults to the same name as the source_paths)"
    required: false
  fonts_path:
    description: "Path to the fonts directory used by the Typst compiler"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source_paths }}
    - ${{ inputs.output_paths }}
    - ${{ inputs.fonts_path }}